### ISSUE TITLE
send_start passes args wrong to _call 

### ISSUE THREAD

**Issue by mielosz** [ChristopherRogers1991/python-irsend#4]
in method send_start:
when address is set it goes as a third positional argument to _call method (device)

in result send_start is called with '-d' option instead of '-a'

Solution: pass 'None' as a 2nd arg of _call, the same way as in send_stop method

**Comment by ChristopherRogers1991** [comment]
Hey @mielosz,

Thanks for catching this and reporting it. This has been fixed in 1.0.2 (https://pypi.org/project/py-irsend/1.0.2/). Please let me know if you have any more issues.

-Chris

**Comment by mielosz** [comment]
Hello @ChristopherRogers1991 ,

Thanks for fixing it. It's working great now :smile: 

Milosz
